/* ============================================================
   SÔMEN — Catálogo de produtos e dados da marca
   Cuidado masculino pra homem se sentir resolvido.
   ============================================================ */

const SOMEN = {
  brand: {
    name: 'SÔMEN',
    tagline: 'Cuidado masculino pra homem se sentir resolvido.',
    manifesto: 'Se cuidar é o mínimo. Ficar no prumo é seu.',
    place: 'BRASIL · SÃO PAULO · MEN CARE',
    phone: '19 1234-4567',
    email: 'contato@somen.com.br',
    instagram: '@somen',
    coupon: 'PRUMO10',
    freeShippingFrom: 199,
  },

  // Categorias da loja
  categories: [
    { id: 'cabelo', label: 'CABELO', desc: 'Shampoo, condicionador e leave-in', img: 'assets/img/leavein.jpg', tone: 'cream' },
    { id: 'barba', label: 'BARBA', desc: 'Óleo multi e cuidado do rosto', img: 'assets/img/oleo.jpg', tone: 'dark' },
    { id: 'finalizacao', label: 'FINALIZAÇÃO', desc: 'Pomada de efeito seco', img: 'assets/img/pomada.jpg', tone: 'cream' },
  ],

  products: [
    {
      id: 'shampoo',
      name: 'Shampoo',
      role: 'O Purificador de Identidade',
      category: 'CABELO',
      cats: ['CABELO', 'BARBA'],
      price: 89.0,
      compareAt: 99.0,
      size: '125ml',
      uses: 'Cabelo · Corpo · Barba',
      badge: 'MAIS VENDIDO',
      img: 'assets/img/shampoo.jpg',
      tone: 'cream',
      rating: 4.9,
      reviews: 214,
      short: 'Remove a sujeira e a crosta da padronização genérica. O primeiro passo de reconexão com a própria força.',
      desc: 'Não é sobre lavar por lavar. O Shampoo SÔMEN limpa fundo sem ressecar — tira o excesso do couro cabeludo, não a força do fio. Fórmula sem sulfato agressivo, feita pra uso diário em cabelo, corpo e barba. O primeiro passo pra voltar no seu prumo.',
      benefits: [
        'Limpa fundo sem ressecar o couro',
        'Sem sulfato agressivo — pode usar todo dia',
        '3 em 1: cabelo, corpo e barba',
        'Testado na cadeira, por quem vive a barbearia',
      ],
      howto: [
        'Molhe bem os fios antes de aplicar — shampoo em cabelo seco trabalha o dobro pra render a metade.',
        'Massageie o couro cabeludo por 30 segundos. É ali que mora o excesso, não nas pontas.',
        'Enxágue por completo. Se sobrar escorregadio no fio, ainda tem produto — repita o enxágue.',
      ],
    },
    {
      id: 'condicionador',
      name: 'Condicionador',
      role: 'O Selador de Estampa',
      category: 'CABELO',
      cats: ['CABELO'],
      price: 79.0,
      compareAt: null,
      size: '125ml',
      uses: 'Cabelo · Barba',
      badge: null,
      img: 'assets/img/condicionador.jpg',
      tone: 'cream',
      rating: 4.8,
      reviews: 156,
      short: 'Sela e protege o que o shampoo abriu. Devolve maciez e firmeza sem pesar no fio.',
      desc: 'O condicionador que fecha a cutícula e recupera o que a rotina castiga. Deixa o cabelo e a barba macios, alinhados e com aquele toque de quem se cuida — sem deixar aquela sensação pesada de produto. Feito pra selar a estampa que é sua.',
      benefits: [
        'Fecha a cutícula e sela a hidratação',
        'Desembaraça sem pesar',
        'Serve pra cabelo e barba',
        'Toque seco, nada de fio engordurado',
      ],
      howto: [
        'Depois do shampoo, tire o excesso de água com a mão.',
        'Aplique do meio às pontas — o couro não precisa de condicionador.',
        'Deixe agir 1 minuto e enxágue. Menos é mais.',
      ],
    },
    {
      id: 'leavein',
      name: 'Leave-In',
      role: 'O Guardião do Prumo',
      category: 'CABELO',
      cats: ['CABELO', 'FINALIZAÇÃO', 'BARBA'],
      price: 69.0,
      compareAt: null,
      size: '125ml',
      uses: '2 em 1 · Cabelo e Barba',
      badge: 'NOVO',
      img: 'assets/img/leavein.jpg',
      tone: 'cream',
      rating: 4.7,
      reviews: 98,
      short: '2 em 1: higienização e força pra cabelo e barba. Mantém o prumo o dia todo, mesmo sob pressão.',
      desc: 'O passo que separa quem se arruma de quem fica no prumo. Sem enxágue: controla o frizz, dá leveza e mantém a barba e o cabelo no lugar do banho ao fim do dia. Não engordura, não endurece — só segura o que é seu.',
      benefits: [
        'Não precisa enxaguar — aplica e pronto',
        'Controla frizz e alinha cabelo e barba',
        'Leveza o dia todo, sem toque pesado',
        'Proteção pra rotina puxada',
      ],
      howto: [
        'Com o cabelo úmido ou seco, pingue de 2 a 3 bombadas na mão.',
        'Distribua no comprimento do cabelo e na barba.',
        'Modele com os dedos. Sem enxágue — o prumo fica.',
      ],
    },
    {
      id: 'pomada',
      name: 'Pomada Modeladora',
      role: 'A Forja do Estilo',
      category: 'FINALIZAÇÃO',
      cats: ['FINALIZAÇÃO'],
      price: 74.0,
      compareAt: 84.0,
      size: '125ml',
      uses: 'Efeito Seco',
      badge: null,
      img: 'assets/img/pomada.jpg',
      tone: 'cream',
      rating: 4.9,
      reviews: 187,
      short: 'Efeito seco, fixação de verdade. Modela sem engordurar e sem endurecer o fio como cimento.',
      desc: 'A pomada de quem quer resultado de barbearia em casa. Efeito seco, matte, com fixação firme que segura o dia inteiro e ainda dá pra remodelar. Não deixa o cabelo duro nem oleoso — molda, dá textura e mantém no prumo.',
      benefits: [
        'Efeito seco e acabamento matte',
        'Fixação firme, mas remodelável',
        'Não engordura nem endurece o fio',
        'Sai fácil no próximo banho',
      ],
      howto: [
        'Aplique no cabelo seco ou levemente úmido.',
        'Pegue uma quantidade do tamanho de uma ervilha e esfregue entre as mãos.',
        'Modele da raiz às pontas, dando o formato. Reforce onde precisar.',
      ],
    },
    {
      id: 'oleo',
      name: 'Óleo Multi',
      role: 'O Fio Condutor',
      category: 'BARBA',
      cats: ['BARBA', 'CABELO'],
      price: 59.0,
      compareAt: null,
      size: '35ml',
      uses: 'Cabelo e barba · Proteção térmica',
      badge: 'NOVO',
      img: 'assets/img/oleo.jpg',
      tone: 'dark',
      rating: 4.8,
      reviews: 73,
      short: 'Cabelo e barba com proteção térmica. Uma gota alinha, controla o frizz e sela as pontas.',
      desc: 'Multiuso de verdade: hidrata a barba, alinha o cabelo e protege do calor do secador e da chapinha. Absorção rápida, sem deixar aquele brilho gorduroso. Uma gota resolve — o fio condutor entre o cuidado e o resultado.',
      benefits: [
        'Proteção térmica pro secador e chapinha',
        'Hidrata a barba e alinha o cabelo',
        'Absorção rápida, sem brilho gorduroso',
        'Rende muito — uma gota por uso',
      ],
      howto: [
        'Com a barba ou o cabelo secos, pingue de 2 a 3 gotas na mão.',
        'Esfregue as mãos e distribua no comprimento.',
        'Antes do secador, aplique pra garantir a proteção térmica.',
      ],
    },
    {
      id: 'kit',
      name: 'Rotina Completa',
      role: 'O Sistema Inteiro',
      category: 'KITS',
      cats: ['KITS', 'CABELO', 'FINALIZAÇÃO'],
      price: 289.0,
      compareAt: 339.0,
      size: '4 produtos',
      uses: 'Do banho ao prumo',
      badge: 'ECONOMIZE R$ 50',
      img: 'assets/img/kit.jpg',
      tone: 'cream',
      rating: 5.0,
      reviews: 64,
      short: 'Shampoo, condicionador, leave-in e pomada na sequência certa. Numa caixa só.',
      desc: 'A rotina inteira, sem você precisar pensar. Shampoo pra purificar, condicionador pra selar, leave-in pra guardar o prumo e pomada pra forjar o estilo — os quatro passos que a barbearia usa, na caixa que chega na sua casa. Simplicidade como respeito ao seu tempo.',
      benefits: [
        'Os 4 passos da rotina numa caixa',
        'Economia de R$ 50 frente ao avulso',
        'A sequência certa, pronta pra seguir',
        'Embalagem que já é presente',
      ],
      howto: [
        'No banho: Shampoo e Condicionador, nessa ordem.',
        'Fora do banho: Leave-In pra guardar o prumo.',
        'Pra sair: Pomada pra forjar o estilo do dia.',
      ],
      contains: ['shampoo', 'condicionador', 'leavein', 'pomada'],
    },
  ],

  // Depoimentos — o barbeiro parceiro e clientes
  testimonials: [
    { name: 'Renan Alves', place: 'Studio Mineiros Barber · Itu/SP', role: 'Barbeiro parceiro', text: 'Uso na minha bancada há dois anos. Cliente pergunta o que é, eu conto a história — e ele leva pra casa.', rating: 5 },
    { name: 'Diego A.', place: 'Belo Horizonte/MG', role: 'Cliente', text: 'Não é frescura. Shampoo, leave-in e pomada e tô resolvido em cinco minutos. Simples do jeito que tem que ser.', rating: 5 },
    { name: 'Lucas C.', place: 'São Paulo/SP', role: 'Cliente', text: 'O óleo multi virou item fixo. Hidrata a barba e ainda protege o cabelo do secador. Rende demais.', rating: 5 },
  ],
};

// ---- Helpers de catálogo ----
SOMEN.find = (id) => SOMEN.products.find((p) => p.id === id);
SOMEN.byCategory = (cat) =>
  cat === 'TODOS' ? SOMEN.products : SOMEN.products.filter((p) => p.cats.includes(cat));

if (typeof window !== 'undefined') window.SOMEN = SOMEN;
